### ISSUE TITLE
Add C++ code

### ISSUE THREAD

**Issue by khagapati-bagh** [khagapati-bagh/hacktoberfest2k21#3]

**Comment by Hussain6** [comment]
Can I do this and what sort of C++ code do you want?

**Comment by khagapati-bagh** [comment]
Hi @Hussain6 
yes, you can do it, add a directory inside the C++ as Algorithm/Sorting and add some sorting algorithm.
Make sure the code should be clean so that anyone can understand and at the top of your file you can mention the time and space complexity of your algorithm.

**Comment by Hussain6** [comment]
Sorting Algorithm has been Added PR #10

**Comment by virajshitole** [comment]
yes, I will add ternary search algorithm. can you assign this issue to me?
